Repository statelyai/xstate, pull requests merged in 2023-09, with the labels that each got.

#3282 Drop support for handling promises returned by `fromCallback`
  .changeset/gentle-bikes-burn.md
  packages/core/src/actors/callback.ts
  packages/core/test/invoke.test.ts
  packages/core/test/types.test.ts
Labels: XState v5 essential

#4278 Improve types for `self`
  .changeset/healthy-pumas-pretend.md
  packages/core/src/actions/assign.ts
  packages/core/src/actions/cancel.ts
  packages/core/src/actions/choose.ts
  packages/core/src/actions/invoke.ts
  packages/core/src/actions/log.ts
  packages/core/src/actions/pure.ts
  packages/core/src/actions/raise.ts
  packages/core/src/actions/send.ts
  packages/core/src/actions/stop.ts
  packages/core/src/scxml.ts
  packages/core/src/stateUtils.ts
  packages/core/src/types.ts
  packages/core/test/types.test.ts
  packages/xstate-immer/src/index.ts
Labels: XState v5 essential

#4274 Add tests for restarting actors within a macrotask
  packages/core/test/actor.test.ts
  packages/core/test/invoke.test.ts
  packages/core/test/predictableExec.test.ts
Labels: XState v5 essential

#4314 add example with persistence saving to mongodb
  examples/mongodb-persisted-state/.gitignore
  examples/mongodb-persisted-state/donutMachine.ts
  examples/mongodb-persisted-state/main.ts
  examples/mongodb-persisted-state/package.json
  examples/mongodb-persisted-state/pnpm-lock.yaml
  examples/mongodb-persisted-state/tsconfig.json
  examples/mongodb-persisted-state/yarn.lock
Labels: example

#4313 Add warning for missing top-level output
  packages/core/src/StateMachine.ts
  packages/core/test/invoke.test.ts
  packages/core/test/json.test.ts
Labels: XState v5 nice to have

#4307 Persist callback input
  .changeset/wise-eggs-train.md
  packages/core/src/actors/callback.ts
  packages/core/test/actorLogic.test.ts
Labels: XState v5 essential

#4172 [v5] `onSnapshot` for all actors
  .changeset/mean-pianos-explode.md
  packages/core/src/Machine.ts
  packages/core/src/actions/invoke.ts
  packages/core/src/actors/observable.ts
  packages/core/src/spawn.ts
  packages/core/src/types.ts
  packages/core/test/actor.test.ts
  packages/core/test/interpreter.test.ts
  packages/core/test/invoke.test.ts
Labels: XState v5 essential
